<a href="https://colab.research.google.com/github/SanjibKarunaChaitanyaGhosh/Machine-Learning-Model/blob/main/Machine_Learning_breast_cancer_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Link Kaggle dataset with collab without download datasets

In [203]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

In [204]:
!kaggle datasets download -d uciml/breast-cancer-wisconsin-data

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
License(s): CC-BY-NC-SA-4.0
breast-cancer-wisconsin-data.zip: Skipping, found more recently modified local copy (use --force to force download)

# 2. Import DATASET

In [205]:
import numpy as np
import pandas as pd

In [206]:
breast = pd.read_csv("/content/breast-cancer-wisconsin-data.zip")

In [207]:
breast.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

**Benign** -- > Cancer Positive                                  
**Malignant** --> Cancer Negative

In [208]:
breast['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

# 3. ASK six questions

In [209]:
breast.shape

(569, 33)

In [210]:
breast.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [211]:
breast.drop('Unnamed: 32',axis=1,inplace=True)

In [212]:
breast.shape

(569, 32)

In [213]:
breast.duplicated().sum()

np.int64(0)

In [214]:
breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

# 4. Encoding The Target Varible

## from sklearn.preprocessing import LabelEncoder
## le = LabelEncoder()

In [215]:
breast['diagnosis'] = breast['diagnosis'].map({'M':'1','B':'0'})

In [216]:
breast.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [217]:
breast.corr()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
id,1.000000,0.039769,0.074626,0.099770,0.073159,0.096893,-0.012968,0.000096,0.050080,0.044158,...,0.082405,0.064720,0.079986,0.107187,0.010338,-0.002968,0.023203,0.035174,-0.044224,-0.029866
diagnosis,0.039769,1.000000,0.730029,0.415185,0.742636,0.708984,0.358560,0.596534,0.696360,0.776614,...,0.776454,0.456903,0.782914,0.733825,0.421465,0.590998,0.659610,0.793566,0.416294,0.323872
radius_mean,0.074626,0.730029,1.000000,0.323782,0.997855,0.987357,0.170581,0.506124,0.676764,0.822529,...,0.969539,0.297008,0.965137,0.941082,0.119616,0.413463,0.526911,0.744214,0.163953,0.007066
texture_mean,0.099770,0.415185,0.323782,1.000000,0.329533,0.321086,-0.023389,0.236702,0.302418,0.293464,...,0.352573,0.912045,0.358040,0.343546,0.077503,0.277830,0.301025,0.295316,0.105008,0.119205
perimeter_mean,0.073159,0.742636,0.997855,0.329533,1.000000,0.986507,0.207278,0.556936,0.716136,0.850977,...,0.969476,0.303038,0.970387,0.941550,0.150549,0.455774,0.563879,0.771241,0.189115,0.051019
area_mean,0.096893,0.708984,0.987357,0.321086,0.986507,1.000000,0.177028,0.498502,0.685983,0.823269,...,0.962746,0.287489,0.959120,0.959213,0.123523,0.390410,0.512606,0.722017,0.143570,0.003738
smoothness_mean,-0.012968,0.358560,0.170581,-0.023389,0.207278,0.177028,1.000000,0.659123,0.521984,0.553695,...,0.213120,0.036072,0.238853,0.206718,0.805324,0.472468,0.434926,0.503053,0.394309,0.499316
compactness_mean,0.000096,0.596534,0.506124,0.236702,0.556936,0.498502,0.659123,1.000000,0.883121,0.831135,...,0.535315,0.248133,0.590210,0.509604,0.565541,0.865809,0.816275,0.815573,0.510223,0.687382
concavity_mean,0.050080,0.696360,0.676764,0.302418,0.716136,0.685983,0.521984,0.883121,1.000000,0.921391,...,0.688236,0.299879,0.729565,0.675987,0.448822,0.754968,0.884103,0.861323,0.409464,0.514930
concave points_mean,0.044158,0.776614,0.822529,0.293464,0.850977,0.823269,0.553695,0.831135,0.921391,1.000000,...,0.830318,0.292752,0.855923,0.809630,0.452753,0.667454,0.752399,0.910155,0.375744,0.368661
symmetry_mean,-0.022114,0.330499,0.147741,0.071401,0.183027,0.151293,0.557775,0.602641,0.500667,0.462497,...,0.185728,0.090651,0.219169,0.177193,0.426675,0.473200,0.433721,0.430297,0.699826,0.438413
fractal_dimension_mean,-0.052511,-0.012838,-0.311631,-0.076437,-0.261477,-0.283110,0.584792,0.565369,0.336783,0.166917,...,-0.253691,-0.051269,-0.205151,-0.231854,0.504942,0.458798,0.346234,0.175325,0.334019,0.767297
radius_se,0.143048,0.567134,0.679090,0.275869,0.691765,0.732562,0.301467,0.497473,0.631925,0.698050,...,0.715065,0.194799,0.719684,0.751548,0.141919,0.287103,0.380585,0.531062,0.094543,0.049559
texture_se,-0.007526,-0.008303,-0.097317,0.386358,-0.086761,-0.066280,0.068406,0.046205,0.076218,0.021480,...,-0.111690,0.409003,-0.102242,-0.083195,-0.073658,-0.092439,-0.068956,-0.119638,-0.128215,-0.045655
perimeter_se,0.137331,0.556141,0.674172,0.281673,0.693135,0.726628,0.296092,0.548905,0.660391,0.710650,...,0.697201,0.200371,0.721031,0.730713,0.130054,0.341919,0.418899,0.554897,0.109930,0.085433
area_se,0.177742,0.548236,0.735864,0.259845,0.744983,0.800086,0.246552,0.455653,0.617427,0.690299,...,0.757373,0.196497,0.761213,0.811408,0.125389,0.283257,0.385100,0.538166,0.074126,0.017539
smoothness_se,0.096781,-0.067016,-0.222600,0.006614,-0.202694,-0.166777,0.332375,0.135299,0.098564,0.027653,...,-0.230691,-0.074743,-0.217304,-0.182195,0.314457,-0.055558,-0.058298,-0.102007,-0.107342,0.101480
compactness_se,0.033961,0.292999,0.206000,0.191975,0.250744,0.212583,0.318943,0.738722,0.670279,0.490424,...,0.204607,0.143003,0.260516,0.199371,0.227394,0.678780,0.639147,0.483208,0.277878,0.590973
concavity_se,0.055239,0.253730,0.194204,0.143293,0.228082,0.207660,0.248396,0.570517,0.691270,0.439167,...,0.186904,0.100241,0.226680,0.188353,0.168481,0.484858,0.662564,0.440472,0.197788,0.439329
concave points_se,0.078768,0.408042,0.376169,0.163851,0.407217,0.372320,0.380676,0.642262,0.683260,0.615634,...,0.358127,0.086741,0.394999,0.342271,0.215351,0.452888,0.549592,0.602450,0.143116,0.310655
symmetry_se,-0.017306,-0.006522,-0.104321,0.009127,-0.081629,-0.072497,0.200774,0.229977,0.178009,0.095351,...,-0.128121,-0.077473,-0.103753,-0.110343,-0.012662,0.060255,0.037119,-0.030413,0.389402,0.078079
fractal_dimension_se,0.025725,0.077972,-0.042641,0.054458,-0.005523,-0.019887,0.283607,0.507318,0.449301,0.257584,...,-0.037488,-0.003195,-0.001000,-0.022736,0.170568,0.390159,0.379975,0.215204,0.111094,0.591328
radius_worst,0.082405,0.776454,0.969539,0.352573,0.969476,0.962746,0.213120,0.535315,0.688236,0.830318,...,1.000000,0.359921,0.993708,0.984015,0.216574,0.475820,0.573975,0.787424,0.243529,0.093492
texture_worst,0.064720,0.456903,0.297008,0.912045,0.303038,0.287489,0.036072,0.248133,0.299879,0.292752,...,0.359921,1.000000,0.365098,0.345842,0.225429,0.360832,0.368366,0.359755,0.233027,0.219122
perimeter_worst,0.079986,0.782914,0.965137,0.358040,0.970387,0.959120,0.238853,0.590210,0.729565,0.855923,...,0.993708,0.365098,1.000000,0.977578,0.236775,0.529408,0.618344,0.816322,0.269493,0.138957
area_worst,0.107187,0.733825,0.941082,0.343546,0.941550,0.959213,0.206718,0.509604,0.675987,0.809630,...,0.984015,0.345842,0.977578,1.000000,0.209145,0.438296,0.543331,0.747419,0.209146,0.079647
smoothness_worst,0.010338,0.421465,0.119616,0.077503,0.150549,0.123523,0.805324,0.565541,0.448822,0.452753,...,0.216574,0.225429,0.236775,0.209145,1.000000,0.568187,0.518523,0.547691,0.493838,0.617624
compactness_worst,-0.002968,0.590998,0.413463,0.277830,0.455774,0.390410,0.472468,0.865809,0.754968,0.667454,...,0.475820,0.360832,0.529408,0.438296,0.568187,1.000000,0.892261,0.801080,0.614441,0.810455
concavity_worst,0.023203,0.659610,0.526911,0.301025,0.563879,0.512606,0.434926,0.816275,0.884103,0.752399,...,0.573975,0.368366,0.618344,0.543331,0.518523,0.892261,1.000000,0.855434,0.532520,0.686511
concave points_worst,0.035174,0.793566,0.744214,0.295316,0.771241,0.722017,0.503053,0.815573,0.861323,0.910155,...,0.787424,0.359755,0.816322,0.747419,0.547691,0.801080,0.855434,1.000000,0.502528,0.511114
symmetry_worst,-0.044224,0.416294,0.163953,0.105008,0.189115,0.143570,0.394309,0.510223,0.409464,0.375744,...,0.243529,0.233027,0.269493,0.209146,0.493838,0.614441,0.532520,0.502528,1.000000,0.537848
fractal_dimension_worst,-0.029866,0.323872,0.007066,0.119205,0.051019,0.003738,0.499316,0.687382,0.514930,0.368661,...,0.093492,0.219122,0.138957,0.079647,0.617624,0.810455,0.686511,0.511114,0.537848,1.000000

# 5. Splitting Data into Training and Testing Sets

In [218]:
breast.shape

(569, 32)

In [219]:
X = breast.drop('diagnosis',axis=1)
y = breast['diagnosis']

In [220]:
X.shape

(569, 31)

In [221]:
y.shape

(569,)

In [222]:
from sklearn.model_selection import train_test_split

In [223]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [224]:
X_train.shape

(455, 31)

In [225]:
X_test.shape

(114, 31)

In [226]:
X_train

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
68,859471,9.029,17.33,58.79,250.5,0.10660,0.14130,0.31300,0.04375,0.2111,...,10.310,22.65,65.50,324.7,0.14820,0.43650,1.25200,0.17500,0.4228,0.11750
181,873593,21.090,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,...,26.680,33.48,176.50,2089.0,0.14910,0.75840,0.67800,0.29030,0.4098,0.12840
63,859196,9.173,13.86,59.20,260.9,0.07721,0.08751,0.05988,0.02180,0.2341,...,10.010,19.23,65.59,310.1,0.09836,0.16780,0.13970,0.05087,0.3282,0.08490
248,88466802,10.650,25.22,68.01,347.0,0.09657,0.07234,0.02379,0.01615,0.1897,...,12.250,35.19,77.98,455.7,0.14990,0.13980,0.11250,0.06136,0.3409,0.08147
60,858970,10.170,14.88,64.55,311.9,0.11340,0.08061,0.01084,0.01290,0.2743,...,11.020,17.45,69.86,368.6,0.12750,0.09866,0.02168,0.02579,0.3557,0.08020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,859711,8.888,14.64,58.79,244.0,0.09783,0.15310,0.08606,0.02872,0.1902,...,9.733,15.67,62.56,284.4,0.12070,0.24360,0.14340,0.04786,0.2254,0.10840
106,863031,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,...,13.140,29.26,85.51,521.7,0.16880,0.26600,0.28730,0.12180,0.2806,0.09097
270,8910721,14.290,16.82,90.30,632.6,0.06429,0.02675,0.00725,0.00625,0.1508,...,14.910,20.65,94.44,684.6,0.08567,0.05036,0.03866,0.03333,0.2458,0.06120
435,908489,13.980,19.62,91.12,599.5,0.10600,0.11330,0.11260,0.06463,0.1669,...,17.040,30.80,113.90,869.3,0.16130,0.35680,0.40690,0.18270,0.3179,0.10550
102,862965,12.180,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.01770,0.1739,...,13.340,32.84,84.58,547.8,0.11230,0.08862,0.11450,0.07431,0.2694,0.06878

# 6. Feature Scaling

In [227]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [228]:
sc.fit(X_train)

StandardScaler()

In [229]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [230]:
X_test

array([[-0.24295555, -0.46649743, -0.13728933, ..., -0.19435087,
         0.17275669,  0.20372995],
       [-0.23712621,  1.36536344,  0.49866473, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [-0.24355432,  0.38006578,  0.06921974, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.23693649, -0.73547237, -0.99852603, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [-0.23694721,  0.02898271,  2.0334026 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 0.42868759,  1.87216885,  2.80077153, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [231]:
X_train

array([[-0.23712699, -1.44075296, -0.43531947, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [-0.23702031,  1.97409619,  1.73302577, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-0.23712907, -1.39998202, -1.24962228, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [-0.17630431,  0.04880192, -0.55500086, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.23675669, -0.03896885,  0.10207345, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.2371006 , -0.54860557,  0.31327591, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

# 7. Training Model

In [232]:
from sklearn.linear_model import LogisticRegression

In [233]:
lg=LogisticRegression()

In [234]:
lg.fit(X_train,y_train)

LogisticRegression()

In [235]:
y_pred = lg.predict(X_test)

In [236]:
y_pred

array(['0', '1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '1', '0',
       '1', '0', '1', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1', '0', '1',
       '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1',
       '0', '0', '0', '0', '0', '1', '1', '0', '0', '1', '1', '0', '0',
       '0', '1', '1', '0', '0', '1', '1', '0', '1', '0', '0', '0', '0',
       '0', '0', '1', '0', '1', '1', '1', '1', '1', '1', '0', '0', '0',
       '0', '0', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1', '1',
       '0', '0', '0', '1', '0', '0', '1', '0', '1', '1'], dtype=object)

## Comparing

In [237]:
from sklearn.metrics import accuracy_score

In [238]:
accuracy_score(y_test,y_pred)

0.9736842105263158

#8. Prediction System

In [239]:
X_train[0]

array([-0.23712699, -1.44075296, -0.43531947, -1.36208497, -1.1391179 ,
        0.78057331,  0.71892128,  2.82313451, -0.11914956,  1.09266219,
        2.45817261, -0.26380039, -0.01605246, -0.47041357, -0.47476088,
        0.83836493,  3.25102691,  8.43893667,  3.39198733,  2.62116574,
        2.06120787, -1.23286131, -0.47630949, -1.24792009, -0.97396758,
        0.72289445,  1.18673232,  4.67282796,  0.9320124 ,  2.09724217,
        1.88645014])

In [243]:
X_test[2]

array([-0.24355432,  0.38006578,  0.06921974,  0.40410139,  0.26659607,
        0.96752014,  0.35641445,  0.72690205,  0.85722095,  0.43709369,
       -0.66605282,  0.25555697, -0.77018483,  0.11394607,  0.17460653,
       -0.24531887, -0.58082836, -0.14617367, -0.15331827, -0.80895985,
       -0.48829815,  0.62940306,  0.07663816,  0.53383214,  0.49204412,
        1.00046591, -0.08616295,  0.4996247 ,  0.57035018, -0.10783139,
       -0.20629287])

In [244]:
y_test[2]

'1'

In [250]:
input_text = [-0.23712699, -1.44075296, -0.43531947, -1.36208497, -1.1391179 ,
        0.78057331,  0.71892128,  2.82313451, -0.11914956,  1.09266219,
        2.45817261, -0.26380039, -0.01605246, -0.47041357, -0.47476088,
        0.83836493,  3.25102691,  8.43893667,  3.39198733,  2.62116574,
        2.06120787, -1.23286131, -0.47630949, -1.24792009, -0.97396758,
        0.72289445,  1.18673232,  4.67282796,  0.9320124 ,  2.09724217,
        1.88645014]
np_df=np.asanyarray(input_text)
prediction  = lg.predict(np_df.reshape(1,-1))
print(prediction)
print(type(prediction[0]))
if prediction[0]=='1':
  print("Cancrous")
else :
  print("Not Cancrous")

['0']
<class 'str'>
Not Cancrous

# 1 = Cancerous (Malignant)
# 0 = Not Cancerous (Benign)

In [246]:
print(np.unique(y_train))

['0' '1']

In [247]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

print(data.target_names)

['malignant' 'benign']

# 10. Pickle

In [248]:
import pickle
pickle.dump(lg,open("model.pkl","wb"))